require('dotenv').config();
const Web3 = require('web3');

const project_id = process.env.INFURA_PROJECT_ID;

const web3 = new Web3(new Web3.providers.HttpProvider('https://mainnet.infura.io/v3/' + project_id));

const contractABI = [
    // Add the ABI generated by the truffle compile here
  ];
  const contractAddress = process.env.CONTRACT_ADDRESS;

const contract = new web3.eth.Contract(contractABI, contractAddress);

module.exports = {
  web3,
  contract,
};
